# Generated by Django 4.1 on 2022-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Immobilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("type", models.CharField(blank=True, max_length=150)),
                ("transaction", models.CharField(blank=True, max_length=150)),
                ("city", models.CharField(blank=True, max_length=150)),
                ("postted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
