# Generated by Django 4.1 on 2022-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Immobilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("type", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "transaction",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("thumbnail_url", models.ImageField(upload_to="")),
                ("url", models.URLField()),
                ("price", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
