# Generated by Django 4.1 on 2022-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immobilier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="immobilier",
            name="thumbnail_url",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
